# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development2:
  secret_key_base: 0a5d7b31b44708b2045f3842392d913c4f0387a9a25335a456a5c1da8bc1d1b274c67a6d24e174bcad2dce286f1cbb44fbce82d71163ee77da35aa0ce4bf67d9

development:
  secret_key_base: 0a5d7b31b44708b2045f3842392d913c4f0387a9a25335a456a5c1da8bc1d1b274c67a6d24e174bcad2dce286f1cbb44fbce82d71163ee77da35aa0ce4bf67d9

test:
  secret_key_base: 1e021edb4b52668cc1b0dbdccd9f887d862c06f46fbeef800fd56036cc5ee2d13844146ea647e06881ee7af50ef10283cc57091133e1a7542c4a9e2573ddc851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
